[2025-08-16 22:08:43,235:INFO:main:Welcome to our custom log]
[2025-08-17 22:26:11,890:INFO:main:>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<]
[2025-08-17 22:26:11,891:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-17 22:26:11,892:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-17 22:26:11,892:INFO:common:created directory at: artifacts]
[2025-08-17 22:26:11,893:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-17 22:26:11,893:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-17 22:26:30,190:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-17 22:26:30,461:INFO:main:>>>>>>>>>> stage Data Ingestion stage completed <<<<<<<<<<< 
 
x==============================x]
[2025-08-18 16:39:52,515:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 16:39:52,516:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 16:39:52,517:INFO:common:created directory at: artifacts]
[2025-08-18 16:39:52,518:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:11:14,777:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:11:14,778:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:11:14,779:INFO:common:created directory at: artifacts]
[2025-08-18 17:11:14,779:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:11:20,581:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:11:20,583:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:11:20,583:INFO:common:created directory at: artifacts]
[2025-08-18 17:11:20,584:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:15:02,967:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:15:02,969:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:15:02,969:INFO:common:created directory at: artifacts]
[2025-08-18 17:15:02,970:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:16:34,238:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:16:34,240:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:16:34,240:INFO:common:created directory at: artifacts]
[2025-08-18 17:16:34,241:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:18:41,931:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:18:41,933:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:18:41,933:INFO:common:created directory at: artifacts]
[2025-08-18 17:18:41,934:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:18:59,773:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 17:18:59,800:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 17:18:59,801:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 18:06:28,923:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 18:06:28,925:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 18:06:28,925:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 18:06:28,925:INFO:common:created directory at: artifacts]
[2025-08-18 18:06:28,925:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 18:06:28,925:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 18:06:47,654:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 18:06:47,926:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 18:06:47,926:INFO:main:*******************]
[2025-08-18 18:06:47,926:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 18:06:47,927:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 18:06:47,927:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 18:06:47,927:INFO:common:created directory at: artifacts]
[2025-08-18 18:06:47,928:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 18:06:48,075:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 18:06:48,103:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 18:06:48,104:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 18:06:48,123:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 19:20:00,883:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:20:00,884:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:20:00,885:INFO:common:created directory at: artifacts]
[2025-08-18 19:20:00,886:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:22:11,604:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:22:11,606:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:22:11,606:INFO:common:created directory at: artifacts]
[2025-08-18 19:22:11,607:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:23:02,094:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:23:02,095:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:23:02,096:INFO:common:created directory at: artifacts]
[2025-08-18 19:23:02,096:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:27:45,429:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:27:45,431:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:27:45,432:INFO:common:created directory at: artifacts]
[2025-08-18 19:27:45,432:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:30:26,860:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:30:26,862:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:30:26,863:INFO:common:created directory at: artifacts]
[2025-08-18 19:30:26,863:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:32:37,412:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:32:37,414:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:32:37,414:INFO:common:created directory at: artifacts]
[2025-08-18 19:32:37,415:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:32:57,000:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:32:57,001:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:32:57,002:INFO:common:created directory at: artifacts]
[2025-08-18 19:32:57,002:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:38:52,445:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:38:52,447:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:38:52,447:INFO:common:created directory at: artifacts]
[2025-08-18 19:38:52,448:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:39:12,375:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:39:12,377:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:39:12,377:INFO:common:created directory at: artifacts]
[2025-08-18 19:39:12,378:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:45:06,200:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:45:06,202:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:45:06,203:INFO:common:created directory at: artifacts]
[2025-08-18 19:45:06,203:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:59:25,963:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:59:25,965:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:59:25,965:INFO:common:created directory at: artifacts]
[2025-08-18 19:59:25,966:INFO:common:created directory at: artifacts/training]
[2025-08-18 20:55:38,784:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 20:55:38,785:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:55:38,785:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:55:38,786:INFO:common:created directory at: artifacts]
[2025-08-18 20:55:38,786:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 20:55:38,786:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:55:57,662:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:55:57,922:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 20:55:57,922:INFO:main:*******************]
[2025-08-18 20:55:57,922:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 20:55:57,923:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:55:57,923:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:55:57,923:INFO:common:created directory at: artifacts]
[2025-08-18 20:55:57,923:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 20:55:58,100:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 20:55:58,125:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 20:55:58,126:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 20:55:58,145:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 20:58:37,360:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 20:58:37,360:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:58:37,361:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:58:37,361:INFO:common:created directory at: artifacts]
[2025-08-18 20:58:37,361:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 20:58:37,361:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:59:10,362:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 20:59:10,363:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:59:10,364:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:59:10,364:INFO:common:created directory at: artifacts]
[2025-08-18 20:59:10,364:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 20:59:10,364:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:59:29,624:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:59:29,883:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 20:59:29,883:INFO:main:*******************]
[2025-08-18 20:59:29,883:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 20:59:29,884:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:59:29,885:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:59:29,885:INFO:common:created directory at: artifacts]
[2025-08-18 20:59:29,885:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 20:59:29,885:ERROR:main:"'ConfigBox' object has no attribute 'base_model_path'"]
Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    prepare_base_model.main()
  File "/Users/sneha/MLOps/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/Users/sneha/MLOps/src/cnnClassifier/config/configuration.py", line 46, in get_prepare_base_model_config
    base_model_path=Path(config.base_model_path),
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"
[2025-08-18 21:00:39,610:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 21:00:39,610:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:00:39,611:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:00:39,611:INFO:common:created directory at: artifacts]
[2025-08-18 21:00:39,611:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 21:00:39,611:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:00:59,305:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:00:59,567:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 21:00:59,567:INFO:main:*******************]
[2025-08-18 21:00:59,567:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 21:00:59,568:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:00:59,569:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:00:59,569:INFO:common:created directory at: artifacts]
[2025-08-18 21:00:59,569:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 21:00:59,569:ERROR:main:"'ConfigBox' object has no attribute 'base_model_path'"]
Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    prepare_base_model.main()
  File "/Users/sneha/MLOps/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/Users/sneha/MLOps/src/cnnClassifier/config/configuration.py", line 46, in get_prepare_base_model_config
    base_model_path=Path(config.base_model_path),
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"
[2025-08-18 21:10:00,499:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 21:10:00,500:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:10:00,500:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:10:00,500:INFO:common:created directory at: artifacts]
[2025-08-18 21:10:00,500:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 21:10:00,500:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:10:20,488:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:10:20,727:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 21:10:20,727:INFO:main:*******************]
[2025-08-18 21:10:20,727:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 21:10:20,728:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:10:20,728:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:10:20,728:INFO:common:created directory at: artifacts]
[2025-08-18 21:10:20,728:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 21:10:20,912:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 21:10:20,940:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:10:20,941:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:10:20,962:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 21:12:23,197:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 21:12:23,197:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:12:23,198:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:12:23,198:INFO:common:created directory at: artifacts]
[2025-08-18 21:12:23,198:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 21:12:23,198:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:12:42,329:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:12:42,585:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 21:12:42,585:INFO:main:*******************]
[2025-08-18 21:12:42,585:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 21:12:42,586:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:12:42,586:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:12:42,586:INFO:common:created directory at: artifacts]
[2025-08-18 21:12:42,586:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 21:12:42,778:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 21:12:42,805:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:12:42,806:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:12:42,825:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 21:12:42,825:INFO:main:*******************]
[2025-08-18 21:12:42,825:INFO:main:>>>>>> stage Training started <<<<<<]
[2025-08-18 21:12:42,826:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:12:42,826:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:12:42,826:INFO:common:created directory at: artifacts]
[2025-08-18 21:12:42,826:INFO:common:created directory at: artifacts/training]
[2025-08-18 21:13:01,081:INFO:main:>>>>>> stage Training completed <<<<<<

x==========x]
